### ISSUE TITLE
基本上是个引流软件

### ISSUE THREAD

**Issue by CoderWQ** [520coding/confuse#20]
基本上是个引流软件，注册后秒到期，转移到联系qq上，之后应该就是谈费用了。
建议不要浪费时间了，还整了个中国图标，真的是绝
Receiving objects: 100% (3017/3017), 5.07 GiB | 5.06 MiB/s, done.
clone大小5.07g。

**Comment by yanjinsheng** [comment]
软件涉及编译，刚开始上手有门槛，如果遇到问题还请及时联系
